services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
